# =============================== config/cameras.yaml (пример) ===============================

cameras:
  falcone_receiver_cam2:
    rtsp:
      provider: falcon_eye_receiver
      channel: 2
      subtype: 0
    debug_window: true
    mask:
      crop: [350, 250, 350, 200]
      polygon:
        - [450, 250]
        - [700, 250]
        - [670, 450]
        - [350, 450]

  falcone_main_ip:
    rtsp:
      provider: falcon_eye_camera
      which: main         # main | second
      mode: real          # real | replay
      idc: 1
      ids: 1
    mask:
      crop: [500, 450, 550, 300]
      polygon:
        - [500, 450]
        - [1050, 450]
        - [1050, 750]
        - [500, 650]

  dahua_receiver_cam16:
    rtsp:
      provider: dahua_receiver
      channel: 16
      subtype: 0
    mask:
      crop: [0, 0, 1280, 720]
      polygon:
        - [0, 0]
        - [1279, 0]
        - [1279, 719]
        - [0, 719]

  onvif_gate_cam:
    rtsp:
      provider: onvif
      host_env: ONVIF_GATE_HOST     # эти имена возьмём из env/секретов
      port_env: ONVIF_GATE_PORT     # например 80/8899 (ONVIF), RTSP порт обычно 554
      user_env: ONVIF_GATE_USER
      pass_env: ONVIF_GATE_PASS
    mask:
      crop: [0, 0, 1280, 720]
      polygon:
        - [0, 0]
        - [1279, 0]
        - [1279, 719]
        - [0, 719]