# =============================== config/cameras.yaml (пример) ===============================

 cameras:
   falcone_resiver_cam2:
     rtsp: "${FALCONE_RESIVER_RTSP:-rtsp://admin:PASS@192.168.1.20:554/cam/realmonitor?channel=2&subtype=0}"
     debug_window: true
     mask:
       crop: [350, 250, 350, 200]
       polygon:
         - [450, 250]
         - [700, 250]
         - [670, 450]
         - [350, 450]

   falcone_main_ip:
     rtsp: "${FALCONE_MAIN_RTSP:-rtsp://admin:PASS@192.168.1.10:554/stream?mode=real&idc=1&ids=1}"
     mask:
       crop: [500, 450, 550, 300]
       polygon:
         - [500, 450]
         - [1050, 450]
         - [1050, 750]
         - [500, 650]

   test_video:
     rtsp: "file:./test_video_2.mp4"
     mask:
       crop: [0, 0, 1280, 720]
       polygon:
         - [0, 0]
         - [1279, 0]
         - [1279, 719]
         - [0, 719]