# alembic.ini

[alembic]


# Путь к скриптам миграции
script_location = app/db/migrations

file_template = %%(year)d-%%(month).2d-%%(day).2d_%%(hour).2d-%%(minute).2d-%%(second).2d_%%(slug)s

# Место для хранения версий миграций
version_locations = app/db/migrations/versions

# Установка пути для поиска
prepend_sys_path = .

# Здесь мы заменим URL базы данных на переменные окружения
sqlalchemy.url = postgresql+asyncpg://${USER_PSTGR_USER}:${USER_PSTGR_PASS}@${USER_PSTGR_HOST}:${USER_PSTGR_PORT}/${USER_PSTGR_NAME}

[post_write_hooks]
# Добавим хук для форматирования с помощью black
hooks = black
black.type = console_scripts
black.entrypoint = black
black.options = -l 79 REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
