[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "monitoring"
description = "Backend application"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "Proprietary" }
authors = [
  { name = "dmitrij-el", email = "dmitrijelectro@gmail.com" }
]
dynamic = ["version"]
dependencies = [
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "numpy>=2.3.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "tomlkit>=0.13.3",
    "opencv-python>=4.12.0.88",
    "python-dotenv>=1.1.1",
    "Pillow>=11.3.0",
    "requests>=2.32.5",
    "PyQt6>=6.9.1",
    "cairosvg>=2.8.2",
    "onvif-zeep>=0.2.12",
    "ultralytics>=8.4.7",
    "pytesseract>=0.3.13"
]

[project.optional-dependencies]
dev = [
    "isort",
    "mypy",
    "pytest",
    "pytest-asyncio"
]


[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools_scm]
version_file = "version.txt"

