
services:
  back-user-app:
    user: "1000:1000"
    build:
      context: ..
      dockerfile: Dockerfile
    image: back-user-app:${VERSION_TAG:-dev}
    env_file: ../.env
    container_name: back-user-app
    ports:
      - "55666:55666"
    networks:
      integra_ecosystem_developer_network:
        ipv4_address: 172.113.10.2
    volumes:
      - /anwill_projects/back/user/app/imgs:/app/imgs
      - /anwill_projects/back/user/app/logs:/app/logs
    restart: always
    command: >
      sh -c "alembic -c /app/alembic.ini upgrade head && 
      gunicorn run:app -c gunicorn.conf.py"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:55666/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  integra_ecosystem_developer_network:
    external: True